language: bash

addons:
  apt:
    packages:
    - ccache
    - zsh

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y distcc

script:
  - bash
  - source ./mmode.sh
  - _mmode_self_test
