language: bash

addons:
  apt:
    packages:
    - ccache
    - zsh

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y distcc
  - mkdir -p ~/.distcc/zeroconf/
  - echo "localhost/2" > ~/.distcc/zeroconf/hosts
  - sudo cp ~/.distcc/zeroconf/hosts /etc/distcc/hosts

script:
  - bash ./self_test.sh
  - zsh ./self_test.sh
